# Generated by Django 2.0.5 on 2018-05-24 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='Publish Date')),
                ('company_website', models.URLField()),
            ],
        ),
    ]
