# Generated by Django 2.0.5 on 2018-05-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='number_of_employee',
            field=models.IntegerField(default=1, verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_website',
            field=models.URLField(default='https://www.google.com/', verbose_name='Company Website'),
        ),
    ]
