# Generated by Django 2.0.5 on 2018-05-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20180524_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_description',
            field=models.TextField(default='No Description Available'),
        ),
    ]
