# Generated by Django 2.0.5 on 2018-05-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_company_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_image_url',
            field=models.URLField(default='http://www.gladessheriff.org/media/images/most%20wanted/No%20image%20available.jpg', verbose_name='Company Image URL'),
        ),
    ]
