# Generated by Django 2.0.5 on 2018-05-27 19:18

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('database', '0004_company_company_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
